function [lgraph,options] = VGG_model()

inputsize = [128, 128, 3];
numClasses = 3;

% % define vgg16-based segnet and customize it for image output
% % GA: Eventually go back and approach differently bc matlab wants me to do
% % segnet differently
lgraph = segnetLayers(inputsize,numClasses,'vgg16');
lgraph = removeLayers(lgraph,{'softmax','pixelLabels'});
lgraph = addLayers(lgraph,regressionLayer('Name','regressionLayer'));
lgraph = connectLayers(lgraph,'decoder1_relu_1','regressionLayer');

options = trainingOptions('adam', ...
    'InitialLearnRate',20,...
    'MaxEpochs',30, ...
    'Shuffle','never',...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.9, ...
    'LearnRateDropPeriod',5, ...
    'MiniBatchSize',8, ...
    'Plots','training-progress', ...
    'Verbose',false);

end

